# -*- coding: utf-8 -*-
"""The staffrail content, from his FINAL corrected wireframe (58 screens).

Regenerated by tools/gen from the corrected file. Standing departures,
each enforced by a gate: em-dashes normalised to commas; the EU
hard-block claim replaced with what is true (he reversed it and no
such block exists); department rails report no activity because the
wireframe named work nothing counted; connector rails keep his NAMES
and drop his status dots, because a dot is a claim only the wire
check may make; and the 16b counts rail is replaced, because the
wireframe's mutation counts were placeholder data and a fabricated
number on a live dashboard is the failure class this OS refuses.
"""

RAILS = {
    '8a': (
        ('SEO department , 5 staff',
         'The staff of this department, and their live state, are on the agents grid below, read from the roster. This rail reports no activity: the wireframe version named work nothing counted.'),
    ),
    '8b': (
        ('Why this desk',
         'Same audit depth as a paid crawler tool , but every issue already has an owner (the Technical Engineer) and a fix path , not just a report you have to act on yourself.'),
    ),
    '8c': (
        ('The AEO/GEO edge',
         'Beyond rank tracking , the Analyst runs your own prompts against ChatGPT , Perplexity , Google AI Overviews and Claude to see if you\'re cited , then routes every gap straight to the Content Specialist to close.'),
    ),
    '8d': (
        ('Why one desk for AEO too',
         'Real content teams don\'t have a separate "AEO person" , the same specialist writes the answer-blocks and schema that get you cited by AI , alongside ordinary on-page fixes.'),
    ),
    '8e': (
        ('One-click hand-off',
         'The Strategist finds the opportunity and routes it straight to the Content Specialist\'s queue , no manual hand-off between research and execution.'),
    ),
    '8f': (
        ('Why gated here',
         'Off-page work touches other people and costs paid data , the Link Builder drafts , you approve every send.'),
    ),
    '8g': (
        ('Provider-agnostic',
         'The whole module reads its source + cost tier from here , swap a provider in one place and every screen updates. No provider name is ever hardcoded in the UI.'),
    ),
    '8h': (
        ('Same pattern , every module',
         'Mirrors the Media Buyer OS agents room exactly , autonomy level , data access + cost cap , activity log , per employee. One shared grammar across all 12 modules.'),
    ),
    '9a': (
        ('Marketing department , 4 staff',
         'The staff of this department, and their live state, are on the agents grid below, read from the roster. This rail reports no activity: the wireframe version named work nothing counted.'),
    ),
    '9b': (
        ('Steps 1 , 2 of the pipeline',
         'Segmentation and competitor research feed directly into the concept builder , offer , emotional angle , story , channel , format , exactly what you brief in real life.'),
    ),
    '9c': (
        ('The spine\'s one gate',
         'Nothing gets produced without clearing this room. Approve here and the piece becomes a brief that flows straight to the Creative Director.'),
    ),
    '9d': (
        ('Router , not maker',
         'The Creative Director decides HOW each piece gets made and assigns it to the right tool or human , production itself happens at the Producer\'s desk.'),
    ),
    '9e': (
        ('Every content type , one desk',
         'Blog , web copy , image , video , animation , voice-over , brochure , product photography , packaging , thumbnails , raw shoot scripts , each routes to its assigned AI tool or a human slot , then lands in Drive.'),
    ),
    '9f': (
        ('Steps 6 , 9 of the pipeline',
         'Scheduling via Metricool , newsletter sends , trade-fair print , appointment booking and community replies , all in one desk , all gated before they go out.'),
    ),
    '9g': (
        ('Shared view',
         'One timeline for every piece moving through the pipeline , useful for everyone , not owned by a single desk.'),
    ),
    '9h': (
        ('Same pattern , every module',
         'Tools layer mirrors SEO\'s data-sources screen; Control Room mirrors Media Buyer\'s agents room , one coherent grammar across all 12 modules.'),
    ),
    '11a': (
        ('Commerce dept , 5 staff',
         'The staff of this department, and their live state, are on the agents grid below, read from the roster. This rail reports no activity: the wireframe version named work nothing counted.'),
    ),
    '11b': (
        ('This desk',
         'Reads live stock from the store , flags low/overstock , keeps SKU/EAN clean , drafts reorder proposals. Data is synced , never invented here.'),
        ('Feeds',
         '💵 Pricing cost basis 🔄 Lifecycle stock signal'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '11c': (
        ('This desk',
         'Every price change is a PROPOSAL , never auto-applied. It goes to the same approval gate as every money move in the OS.'),
        ('Slot',
         'PRICE-INTEL PAID'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '11d': (
        ('This desk',
         'Ranks priority sellers , flags slow movers , proposes bundles , and runs comparative product research via the MARKET slot.'),
        ('Feeds',
         'Marketing OS priority products'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '11e': (
        ('This desk',
         'The margin-impact preview is computed before you approve , you see what a discount does to margin before it\'s live , not after.'),
        ('Slot',
         'PROMO = your store , native'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '11f': (
        ('Routes to',
         'restock -> Inventory clearance -> Promotions discontinue -> SKU cleanup'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '11g': (
        ('The bridge',
         'Approved offers and priority products land as concept seeds in Module 3\'s Strategist desk , the two departments become one Mother OS.'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '11h': (
        ('Same pattern , every module',
         'One control room shape across all 12 modules , sources , staff , autonomy , so the whole Mother OS reads as one coherent product.'),
    ),
    '11i': (
        ('This is the API layer',
         'Each pill pulls that platform\'s own reporting system , Amazon FBA\'s IPI/Buy Box , FBM\'s Account Health rates , Meta\'s catalog diagnostics , TikTok\'s GMV-by-surface , never one merged table.'),
        ('After the numbers',
         'Every channel has its own working agent below the chart , stop it , or write it a new instruction directly , without leaving this screen.'),
    ),
    '12a': (
        ('Two gates',
         'Region: Europe and Germany stay IN scope, as you decided. Consent and open-tracking state are the real control, not a country block, and no country block exists in this engine. Send: every campaign needs a named approver before the Sender touches it.'),
        ('Cold is not newsletter',
         'This module is outbound prospecting. The newsletter lives in Marketing ( 9f ).'),
    ),
    '12b': (
        ('This desk',
         'Every source is a slot with a visible cost + risk badge , risky ones (LinkedIn , messaging apps) are flagged ⚠ so you plug a compliant provider instead of raw scraping that gets blocked.'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '12c': (
        ('The region gate',
         'Region: Europe and Germany stay IN scope, as you decided. Consent and open-tracking state are the real control, not a country block, and no country block exists in this engine. Send: every campaign needs a named approver before the Sender touches it.'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '12d': (
        ('Next',
         'Hot leads (score >80) route to the Writer with their persona + best offer angle attached , no blank-slate drafting.'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '12e': (
        ('This desk',
         'The Writer never invents brand voice , template , copy shell , CTA and design come from Marketing. Personalization is per-lead , per-persona only.'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '12f': (
        ('Send is gated',
         'Rate-limited , warmed domains , compliance-checked , human-approved. No auto-blasting , ever.'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '12g': (
        ('Same pattern , every module',
         'Sources , staff , autonomy , one control-room shape across the Mother OS. Here the only non-negotiable defaults are the send gate and the EU block.'),
    ),
    '12h': (
        ('One view , two pipes',
         'Whether the agent drives an ESP like Klaviyo or calls the store\'s own email API , creative , list and metrics render the same way here.'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '12i': (
        ('Segmentation Analyst',
         'Rebuilds lifecycle segments from order history , and tags every prospected lead with its source + location for the Qualifier and Sender to use.'),
        ('Command',
         'Command this desk from the command box on this screen.'),
    ),
    '15a': (
        ('This desk',
         'The surface matrix is the truth: WhatsApp has no public comments , TikTok hides DMs from bots , Telegram comments live in the linked discussion group. The bot never pretends a surface exists.'),
        ('Connectors',
         'WhatsApp Cloud API, Telegram Bot API, Meta Graph (IG+FB), TikTok Business. Live state for each comes from the engine\'s own wire check, never from this drawing.'),
        ('Feeds',
         '💵 Pricing price complaints 🎯 Leads buying-intent DMs 🧠 Strategist recurring questions'),
    ),
    '15b': (
        ('This desk',
         'For FBA , Amazon\'s receiving count is the truth , not the packing list. The OS never edits channel stock silently: every reconciliation and every reimbursement case is a proposal through the gate.'),
        ('Connectors',
         'SP-API FBA Inbound, SP-API Listings, Shopify Admin API, Woo REST API, TikTok Shop API. Live state for each comes from the engine\'s own wire check, never from this drawing.'),
        ('Feeds',
         '💵 Pricing landed cost 🏷 Promotions stock gate'),
    ),
    '15c': (
        ('This desk',
         'Nothing here is invented: every panel is a report that already exists inside that platform\'s seller workspace , Opportunity Explorer & Brand Analytics on Amazon , Industry Insights & Product Diagnosis in TikTok Seller Center , Analytics & Search/Discovery in Shopify admin. The agent\'s only job is pulling , cross-reading and proposing.'),
        ('Applies to',
         'Amazon (FBA/FBM), TikTok Shop, Shopify, WooCommerce. Live state for each comes from the engine\'s own wire check, never from this drawing.'),
        ('Feeds',
         '💵 Pricing Analyst reprice proposals 🧺 Merchandiser research board 🧠 Strategist competitor angles'),
    ),
    '16a': (
        ('Key handling',
         'Public key identifies , private key signs. The private key never leaves the vault , never appears in logs or agent context. Rotation reminder every 90 days. Revoking a key kills every derived agent token instantly.'),
        ('Who gets what',
         '💵 Pricing Analyst prices · read 📦 Inventory Ctrl stock · read+write* 🎯 Qualifier customers · read 💬 Community Mgr order status · read 📊 Analytics all · read * write = proposal through your gate'),
        ('Command this hub',
         '"add our SAP sandbox with these keys" -> form pre-filled "why is Woo stock stale?" -> webhook failure trace'),
    ),
    '16b': (
        ('This view',
         'The ledger is the OS\'s memory: every field carries lineage (source system , version , actor). "Who changed this price and why" is always one click , and one command , away.'),
        ('Mutations by source (today)',
         'One row per source system, counted from the ledger itself once the ledger has a writer. The wireframe\'s counts were placeholder data, so this rail shows the engine\'s real tally or nothing.'),
        ('Command the ledger',
         '"revert every title change from yesterday" -> 4 found , preview "who touched invoice totals this week?" -> Finance pull x3'),
    ),
    '17a': (
        ('How connecting works',
         'Today a credential is pasted in the Tool Hub and vaulted there; the Google tools accept one service-account JSON that powers four wires. His drawing adds sign-in (OAuth), which is not built yet, and its absence is exactly why Google Ads still refuses its pasted client. Agents get scoped read tokens either way, and the dashboard builds from the first pull.'),
        ('Who reads these feeds',
         '🔍 SEO Analyst GSC · GA4 📣 Media Buyer Pixels · GA4 🧠 Strategist GA4 · GTM 📊 Analytics all'),
        ('Command',
         '"connect our second GA4 property" -> sign-in opens "why did pixel events drop Friday?" -> GTM version diff'),
    ),
}


def for_screen(sid):
    """The rail sections for one screen, or () when he drew none."""
    return RAILS.get(str(sid), ())
